---
title: "Business Intelligence Lab Submission Markdown"
author: "Starfield"
date: "07/11/2023>"
output:
  github_document: 
    toc: yes
    toc_depth: 4
    fig_width: 6
    fig_height: 4
    df_print: default
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---


+----------------------------------+----------------------------------+
| **Student ID Numbers and Names   | 1\. 135232 - Sadiki Hamisi       |
| of Group Members**               |                                  |
|                                  | 2\. 134782 - Yasmin Choma        |
|                                  |                                  |
|                                  | 3\. 134783 - Moses mbugua        |
|                                  |                                  |
|                                  | 4\. 122998 - Glenn Oloo          |
+----------------------------------+----------------------------------+
| **GitHub Classroom Group Name**  | Starfield                        |
+----------------------------------+----------------------------------+
| **Course Code**                  | BBT4206                          |
+----------------------------------+----------------------------------+
| **Course Name**                  | Business Intelligence II         |
+----------------------------------+----------------------------------+
| **Program**                      | Bachelor of Business Information |
|                                  | Technology                       |
+----------------------------------+----------------------------------+
| **Semester Duration**            | 21^st^ August 2023 to 28^th^     |
|                                  | November 2023                    |
+----------------------------------+----------------------------------+


**Note:** the following "*KnitR*" options have been set as the
defaults:\
`knitr::opts_chunk$set(echo = TRUE, warning = FALSE, eval = TRUE, collapse = FALSE, tidy.opts = list(width.cutoff = 80), tidy = TRUE)`.

More KnitR options are documented here
<https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html> and
here <https://yihui.org/knitr/options/>.

```{r setup, include=FALSE}
library(formatR)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, eval = TRUE,
                      collapse = FALSE, tidy = TRUE)
```

**Note:** the following "*R Markdown*" options have been set as the
defaults:

Installing and loading of required packages

```{Code Chunk One}
# Language server
if (require("languageserver")) {
  require("languageserver")
} else {
  install.packages("languageserver", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}
# mlbench
if (require("mlbench")) {
  require("mlbench")
} else {
  install.packages("mlbench", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## caret ----
if (require("caret")) {
  require("caret")
} else {
  install.packages("caret", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## kernlab ----
if (require("kernlab")) {
  require("kernlab")
} else {
  install.packages("kernlab", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## randomForest ----
if (require("randomForest")) {
  require("randomForest")
} else {
  install.packages("randomForest", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}
```

Loading the dataset

```{Code Chunk Two}

library(readr)
IRIS <- read_csv("data/IRIS.csv")
View(IRIS)

```

Training the models

```{Code Chunk Three}

train_control <- trainControl(method = "repeatedcv", number = 10, repeats = 3)

### LDA ----
set.seed(7)
IRIS_model_lda <- train(species ~ ., data = IRIS,
                            method = "lda", trControl = train_control)

### CART ----
set.seed(7)
IRIS_model_cart <- train(species ~ ., data = IRIS,
                             method = "rpart", trControl = train_control)

### KNN ----
set.seed(7)
IRIS_model_knn <- train(species ~ ., data = IRIS,
                            method = "knn", trControl = train_control)

### SVM ----
set.seed(7)
IRIS_model_svm <- train(species ~ ., data = IRIS,
                            method = "svmRadial", trControl = train_control)

### Random Forest ----
set.seed(7)
IRIS_model_rf <- train(species ~ ., data = IRIS,
                           method = "rf", trControl = train_control)

```

Calling the re-sampled functions

```{Code Chunk Four}

results <- resamples(list(LDA = IRIS_model_lda, CART = IRIS_model_cart,
                          KNN = IRIS_model_knn, SVM = IRIS_model_svm,
                          RF = IRIS_model_rf))

```

Displaying the results

```{Code Chunk Five}

summary(results)

```

Visualization of the results

```{Code Chunk Six}

# Box and Whisker Plot ----

scales <- list(x = list(relation = "free"), y = list(relation = "free"))
bwplot(results, scales = scales)

# Dot Plots ----

scales <- list(x = list(relation = "free"), y = list(relation = "free"))
dotplot(results, scales = scales)

# Scatter Plot Matrix ----

splom(results)

# Pairwise xyPlots ----

# xyplot plots to compare models
xyplot(results, models = c("LDA", "SVM"))

# or
# xyplot plots to compare models
xyplot(results, models = c("SVM", "CART"))

```


Statistical Significance Tests (lower and upper diagonal)

```{Code Chunk Seven}

diffs <- diff(results)

summary(diffs)

```